"""add accessible flag to seat

Revision ID: 45e4baba020a
Revises: c04d82917920
Create Date: 2026-08-17 16:13:31.025744

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '45e4baba020a'
down_revision = 'c04d82917920'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('accessible', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seat', 'accessible')
    # ### end Alembic commands ###
