"""add event backdrop_path

Revision ID: 4a99c0fbe4d7
Revises: e615e5cc6fe3
Create Date: 2026-08-17 13:48:05.899467

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '4a99c0fbe4d7'
down_revision = 'e615e5cc6fe3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('backdrop_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'backdrop_path')
    # ### end Alembic commands ###
