"""adiciona codigo curto de digitacao manual ao ingresso

Revision ID: 79974c950ebc
Revises: a351f43b0736
Create Date: 2026-08-19 14:14:46.513273

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# identificadores da revisão, usados pelo Alembic.
revision = '79974c950ebc'
down_revision = 'a351f43b0736'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('manual_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_ticket_manual_code'), 'ticket', ['manual_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_manual_code'), table_name='ticket')
    op.drop_column('ticket', 'manual_code')
    # ### end Alembic commands ###
