"""organizador cadastra porteiro direto, remove sistema de cracha

Revision ID: ad4ab2205877
Revises: 79974c950ebc
Create Date: 2026-08-19 14:29:37.773284

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# identificadores da revisão, usados pelo Alembic.
revision = 'ad4ab2205877'
down_revision = '79974c950ebc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_staffcredential_code', table_name='staffcredential')
    op.drop_table('staffcredential')
    op.add_column('user', sa.Column('organizer_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_user_organizer_id_user', 'user', 'user', ['organizer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_user_organizer_id_user', 'user', type_='foreignkey')
    op.drop_column('user', 'organizer_id')
    op.create_table('staffcredential',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', postgresql.ENUM('organizer', 'customer', 'gate', name='userrole', create_type=False), autoincrement=False, nullable=False),
    sa.Column('holder_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('used_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['user.id'], name='staffcredential_used_by_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='staffcredential_pkey')
    )
    op.create_index('ix_staffcredential_code', 'staffcredential', ['code'], unique=True)
    # ### end Alembic commands ###
