"""adiciona data de criacao do evento

Revision ID: bb0097f29284
Revises: ad4ab2205877
Create Date: 2026-08-19 16:04:36.438059

"""
from alembic import op
import sqlalchemy as sa

# identificadores da revisão, usados pelo Alembic.
revision = 'bb0097f29284'
down_revision = 'ad4ab2205877'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default só pra preencher as linhas existentes — o campo
    # continua sendo definido pelo default_factory do Python nas novas.
    op.add_column(
        'event',
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('now()')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'created_at')
    # ### end Alembic commands ###
